### PR TITLE
mirai scheduling with callr workers

### PR DESCRIPTION
**Pull request by wlandau**
# Prework

* [x] I understand and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew/blob/main/CODE_OF_CONDUCT.md).
* [x] I have already submitted a [discussion topic](https://github.com/ropensci/crew/discussions) or [issue](https://github.com/ropensci/crew/issues) to discuss my idea with the maintainer.

# Related GitHub issues and pull requests

* Ref: #26, #28

# Summary

This PR rewrites `crew` using [`mirai`](https://github.com/shikokuchuo/mirai) as the underlying task scheduler. @shikokuchuo, thanks to your hard work on [`mirai`](https://github.com/shikokuchuo/mirai) and [`nanonext`](https://github.com/shikokuchuo/nanonext), `crew` looks much more promising. I really appreciate all the time you spent helping me and implementing new features.

Because of the one-port-per-worker requirement of the active queue, I still intend to write an alternative backend using [`rrq`](https://github.com/mrc-ide/rrq)/Redis as the task scheduler. Either one will eventually win out over the other, or we can keep both and let users decide which one to run. An all-angles approach seems constructive at the moment.

### CODE REVIEW

**Comment by wlandau** [comment]
Tests look good on Unix-like systems, but Windows GitHub Actions runners may have stalled. Not sure why.

**Comment by wlandau** [comment]
I think I'll merge now and then figure out what to do about Windows later.

**Comment by shikokuchuo** [comment]
> Tests look good on Unix-like systems, but Windows GitHub Actions runners may have stalled. Not sure why.

Sometimes on GH tests try to terminate before all background processes exit causing a hang. Just need a suitable sleep towards the end of your tests most likely. Not so common on Winbuilder - but you will need to test there to be sure.

**Comment by wlandau** [comment]
How long of a Sys.sleep() has worked for you?

**Comment by shikokuchuo** [comment]
I am using 3L - but only because I use ephemeral mirai in my tests (non-daemon) and they require 2s to shut down. So I am guessing 1L should be enough in your case.

**Comment by shikokuchuo** [comment]
In case you're wondering about the 2s, it's to guard against the R session being reaped faster than the underlying C code can finish sending say a very large object (e.g. GBs). It can happen! But that only applies to the short-lived mirai which exit after each task, not daemons which run continuously.

**Comment by shikokuchuo** [comment]
I have noticed your use of 'transient' workers by setting `max_tasks = 1L`. I have added the appropriate 2s guard in mirai in [f80e4e6](https://github.com/shikokuchuo/mirai/commit/f80e4e6d07c0dc9cd933bcbc60185e5f2435bd0d) for those processes exiting due to task/time outs, otherwise the daemon can exit before it can send back it's results. So yes, for tests `Sys.sleep(3L)` would probably be a good idea.

**Comment by wlandau** [comment]
Thanks for the tip! Hopefully https://github.com/wlandau/crew/commit/fa924fd5a4f926ce14ba368c8f5548608da2a3cf does the trick.

**Pull request merged**
