### PR TITLE
Changes to enable L'Ecuyer-CMRG Streams

### PR DESCRIPTION
**Pull request by shikokuchuo**
# Prework

* [x] I understand and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew/blob/main/CODE_OF_CONDUCT.md).
* [x] I have already submitted a [discussion topic](https://github.com/ropensci/crew/discussions) or [issue](https://github.com/ropensci/crew/issues) to discuss my idea with the maintainer.

# Related GitHub issues and pull requests

* Ref: #113 

# Summary

Posting this as I was testing the new function to make sure it works as designed.

This is a minimal patch, but a good starting point.

Needs to be fleshed out - docs, tests, dependencies (will need to rely on the latest dev build of mirai and CRAN nanonext 0.10.0) - hope can leave that in your good hands.

### CODE REVIEW

**Comment by shikokuchuo** [comment]
Ah probably a bit more needs to change - the seed and algorithm defaults mask the underlying .Random.seed, I had to set them to NULL to get at it.

**Comment by wlandau** [comment]
Thanks for the PR, @shikokuchuo. I will take it and adjust `push()` and `crew_eval()` to accommodate.

> Ah probably a bit more needs to change - the seed and algorithm defaults mask the underlying .Random.seed, I had to set them to NULL to get at it.

Sorry, I'm not sure I understand.  Are you referring to the defaults in `push()`? I plan to make the default `algorithm` in `push()` equal to `"mirai"`, which will avoid setting either inside the task (`crew_eval()`).

**Comment by wlandau** [comment]
And come to think of it, I should probably restore the seed and algorithm if someone sets non-defaults, in order to restore the widely-spaced L'Ecuyer streams.

**Comment by shikokuchuo** [comment]
> Thanks for the PR, @shikokuchuo. I will take it and adjust `push()` and `crew_eval()` to accommodate.
> 
> > Ah probably a bit more needs to change - the seed and algorithm defaults mask the underlying .Random.seed, I had to set them to NULL to get at it.
> 
> Sorry, I'm not sure I understand. Are you referring to the defaults in `push()`? I plan to make the default `algorithm` in `push()` equal to `"mirai"`, which will avoid setting either inside the task (`crew_eval()`).

Yes, exactly what I meant. And yes algorithm = "mirai" is a nice name for the default.

**Comment by shikokuchuo** [comment]
Great - seems to work. It's feature freeze for `mirai` as of 0.9.1.9025 until the CRAN release. So do get all your testing in!

**Comment by wlandau** [comment]
I just ran through all my tests, and almost everything looks good. Everything is definitely still compatible, and I would go ahead with the next `mirai` release as soon as CRAN allows.

I did encounter a few errors initially, but that may be because my Ubuntu machine couldn't handle the load. It has 4 physical cores and 16 GB memory. I built it back in early 2017.  I usually run `urlchecker`, `lintr`, `testthat`, `covr`, `devtools::check()`, `revdepcheck`, and `goodpractice` all at the same time in different terminal windows.

Running devtools::test():

```r
Error (test-crew_controller_local.R:516:3): map() does not need an started controller
<crew_error/crew/rlang_error/error/condition>
Error: invalid daemons: structure(5L, class = "errorValue")
 The mirai dispatcher is not running. Please call the start() method of the controller (e.g. your_controller$start() before using methods like push(), collect(), and scale(). If you already did, then the dispatcher may have exited too early.
```
 
Running covr::package_coverage():
 
```r
 Error (test-crew_controller_group.R:192:3): crew_controller_group() collect
Error in `launch_and_sync_daemon(sock = sock, urld, parse_dots(...), url, 
    n, urlc, tls = tls)`: initial sync with dispatcher timed out after 5s
```

I also hit a couple segfaults while all this was happening. But again, my computer may have been struggling to keep up.

**Comment by shikokuchuo** [comment]
> I did encounter a few errors initially... I usually run `urlchecker`, `lintr`, `testthat`, `covr`, `devtools::check()`, `revdepcheck`, and `goodpractice` all at the same time in different terminal windows.
> 
**At the same time** - it is probably for this reason  - running all those at the same time will likely lead to issues such as contention on locks etc. There are some settings when the NNG library is built which take into account the core count of the machine.

**Pull request merged**
