### PR TITLE
Update shiny.Rmd

### PR DESCRIPTION
**Pull request by shikokuchuo**
# Prework

* [x] I understand and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew/blob/main/CODE_OF_CONDUCT.md).
* [x] I have already submitted a [discussion topic](https://github.com/ropensci/crew/discussions) or [issue](https://github.com/ropensci/crew/issues) to discuss my idea with the maintainer.

# Related GitHub issues and pull requests

* Ref: #69

# Summary

For efficiency, only poll when there are outstanding tasks. There are many ways to implement so feel free to modify / take what you want.

### CODE REVIEW

**Comment by wlandau** [comment]
Thanks for the suggestion! I took your idea of a reactive and used it to really simplify the concept in 9d73a762bc3f91f1dff153503f22baf9b02908c8 (and added a news entry with an acknowledgement in 65515d7a7a784072712515f4c9eb19c324c1f4d7). Now, the last `observe()` really drives the concept home, and I like the whole app much more. So although I have decided not to merge the literal PR, it was still super helpful.

**Comment by shikokuchuo** [comment]
Looks good! But somehow there is now a mismatch between the written description and the code in terms of     `invalidateLater(millis = 1000)`. I'd suggest to keep it at 250 to be more responsive.

**Comment by wlandau** [comment]
Thanks for catching that, it was left over from my testing code. Should be fixed now.

**Comment by shikokuchuo** [comment]
Almost there - the code block at the end hasn't caught up with the changes you made to the code above (which I really like)!

**Comment by wlandau** [comment]
Thanks for looking. Would you point me to where you still see `millis = 1000`? It took a couple commits, but I thought I got them.

**Comment by shikokuchuo** [comment]
That part’s good. It’s the moving the reactive_poll() statement to the end of the observe block, which I thought was a good call.On 5 May 2023, at 17:44, Will Landau ***@***.***> wrote:﻿
Thanks for looking. Would you point me to where you still see millis = 1000? It took a couple commits, but I thought I got them.

**Comment by wlandau** [comment]
Ah, thanks for clarifying. Should be fixed now.

**Pull request closed without merging**
